### ISSUE TITLE
[3.1 Registration] Can't register with 100 character email attribute

### ISSUE THREAD

**Issue by tubzby** [tubzby/itmd536#9]
The prompt message: "Invalid email format." is also incorrect.

**Comment by Hellboycc** [comment]
Fixed already, commit -> 84983db

**Comment by tubzby** [comment]
using email: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@abc.com

causing error: The email is wrong

@Hellboycc

**Comment by Hellboycc** [comment]
It's limited by the third module and the reference as below:
[RFC 3696 + errata 1003 + errata 1690 ](https://www.rfc-editor.org/errata_search.php?rfc=3696&eid=1690)
please check it.

**Comment by tubzby** [comment]
ok, so please @fokman fix the requirements.
